Add-Type -AssemblyName System.Windows.Forms
[System.Windows.Forms.Application]::EnableVisualStyles()

If (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]'Administrator')) {
    [Void] [System.Windows.Forms.MessageBox]::Show(
        "You're not running this script as Administrator! You should use batch script to launch this script!", 
        "", 
        [System.Windows.Forms.MessageBoxButtons]::OK, 
        [System.Windows.Forms.MessageBoxIcon]::Error
    )
    Exit
}

Function Error([String] $Message)
{
    If (($Message -ne $null) -and ($Message.Length -gt 0))
    {
        $Time = Get-Date -DisplayHint Time
        Write-Host "[$Time] [ERROR] > $Message" -ForegroundColor Red
    }
}

Function Warning([String] $Message)
{
    If (($Message -ne $null) -and ($Message.Length -gt 0))
    {
        $Time = Get-Date -DisplayHint Time
        Write-Host "[$Time] [WARNING] > $Message" -ForegroundColor Yellow
    }
}

Function Log([String] $Message)
{
    If (($Message -ne $null) -and ($Message.Length -gt 0))
    {
        $Time = Get-Date -DisplayHint Time
        Write-Host "[$Time] [LOG] > $Message" -ForegroundColor Cyan
    }
}

Try
{
    $Build = [System.Convert]::ToInt32([System.Environment]::OSVersion.Version.Build)
    If ($Build -lt 16000)
    {
        Error("This script is only meant to be ran on Windows 10 or 11, Build $Build is not supported! Press any key to close this script.")
        If ([System.Console]::ReadKey()) { Exit }
    }
}
Catch
{
    Error("Failed to get Windows Version, exception info : $($_). Press any key to close this script.")
    If ([System.Console]::ReadKey())
    {
        Exit
    }
}

Log("Wait, trying to creating Restore Point..." )
Try
{
    Enable-ComputerRestore -Drive $env:SystemDrive -ErrorAction Stop
    Checkpoint-Computer -Description "BeforeDebloat" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
}
Catch
{
    Error("Failed to create Restore Point, exception : $($_)")
}

$Form                            = New-Object System.Windows.Forms.Form
$Form.ClientSize                 = New-Object System.Drawing.Point(500,570)
$Form.Text                       = "Xercaii Free Tweaking Utility"
$Form.StartPosition              = "CenterScreen"
$Form.BackColor                  = [System.Drawing.ColorTranslator]::FromHtml("#252525")
$Form.ShowIcon                   = $false
$Form.MinimizeBox                = $false
$Form.MaximizeBox                = $false
$Form.FormBorderStyle            = 'FixedSingle'
$Host.UI.RawUI.WindowTitle       = "Xercaii Free Tweaks"
$ErrorActionPreference           = "SilentlyContinue"

$IconBase64                      = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURQ88OxNfDhhcGRhlDRxqGBplExxsFR9yGR1xFiNvDiFtGCd4GiJzFyN0GSt7GzF+GxZNKRlXJRZINhpSNiJdKSVXPBxoJhxxJRt4NyVlJyh4JjN7JSNuNDVqOiR4NTZ2Og86QRU8Rhc7WQ0eew8uZRMqaRQ1aA4gexcrdRY2dyE1YSAvcyk/eBhHSR5WQhtFWChUSTRbTSREVyRSVTFQXx18RxV7VS5hRTZlSCd+SD5xQjxmWSN/Ux5BbyRHaDNSYC1HcCtRdz1kakRpT0Z5SkZufC+BHDiGHDSDHDyLHi+AIDyKJTODIzyQIkCNHkiVHkGOJUiVKUSTIkybJFGeJkaLNEyYMlOcNU+gJVmnKFWjJlmmJ1qmKF2qKVqkOGGtLWOwL2StNGOrPWy3OmaxMmqzNWy1O3C3PnO7PXXAPRyATBqCWyeCSzaFRzyQRiiFVzeHWBeFZxeLeCaJaTWNaC+QaTuSaiWMeTuWek6BSFqbREOMWF6bU16lRGetQmuyR2yzQ3G2RXW8Q3m+RHW7SXq+SmurU3GtVHm1WUWRYkKafkige2W8cXbBQnvBRX7CTX/DUIC2XYW9Y4fHToXGTorKWITGUpHPX5DQXo/GaJPKaZbVaJ3Od57YdqDPeqHYeaThewodihAdgQwdlQ0bnBAfkgwliRMpiAY4ihQxhAsnmxQmmAg3mh40lCA7nA0cpA4dqxAdqQ4esRAfsAstpwwhpQ0iqREipQo4qwoxoQ0ssgs6uAwztQJLjQZFnBtBmQRSmyRBiTVVhQZHogZIowRZqQhItwZXtyVPqQJlqwNquQJzuwlKwQdbxgZkxwJ7xwJywgZr0wR41Q6LhRKNhxuRiBCPkheUlyGOhCaUijeZhyialDOcmA2XqBiZqAqbuRSdtSScqBqjvCmhrjSnqiektDGru0OYgEOdkkq5lEqmpgCFygKDzAmewwGJ1QCU2guiyBSkyQem2hSo2CWoxTKrxAKO4QCe6QGV5ACc4wOl5gCm7QCt7wCr8KbigAAAAAf6iXMAAAEAdFJOU////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////wBT9wclAAAACXBIWXMAAA7DAAAOwwHHb6hkAABcn0lEQVR4Xu29C3wb930nWIvEYEiAYOykK0e++C7ZNHW6Tbp7ba9Nmt7nrtcVKZHi26SIBylR7ya9xM7d5rbXyKJE7HX3TsI4oljHj9St4EcV5QCQIilLstZXydJZb2vb+pLt5dVm72GHcpSuZZFEs7/v7/+fB4gBCEkAycHMl8DMfwYDEJjv9/f4P+Y/P/czD66GJwCXwxOAy+EJwOXwBOByeAJwOTwBuByeAFwOTwAuhycAl8MTgMvhCcDl8ARQPUgmk6lkSm6UCk8AVYFkipFJHj58hwrwBOBgkMnD5lOp5JETJ8+dPnv11tytV5LyxRLhCcCZEMxnUsnk0fNX3rxwdebW3Pwc4dYrngeodghnn06l/vTohffef//27bks/oj/LCnAE0B1At6erB7ufvLYqWOnT8/cIrrBONjHIpudhw/wBFB9kIE+lTr8yrnLV85fvQFfz+TPz81n55l6flBpzssBqgqgPZOhUH/k6PWZ92ZuSHdP9k7UA1AA08+gF454HsDx0J09YXLqxJEX37immzxTztzzQ9JuAHmA5wGcDDAvuE8efuXSpfPnL95ggyfqOceD6TP3+eQzEAI8D+BQCOIzqfThw2euXb/+Drl7hHi2fPh29vmS6AKgN2Q9D+AswN3r1Kcmky++cWOWTZ2o5D9aS4cPLCIAVAM8D+AUGO6eUrzjJy+de/3CbRHokeEh2APgHKwvyrwAvdHzAA6AtPk0Gf2Rs1fevHqN3D0a8sjuRahn2xeUipWOxYTgeYAVD7Z51OwOH3nt/Vu3b82y0XOVHlGeniLWl2jzufA8wEoFu3syeIrzx06ePP4aGnOYeI7yureXkb44ih7jeYAVBz3FS6eSR89duXLl4ju34OSFmxfUC95LYr846DO9doCVBDCfRqj/06MXZt67gUjPzEsFwGNL9ssFryl4+QFvD6tPp1JTx04ce+X02xzjGXD3iPQlevs7BinKE8CyQa/XpSnYTx45d/ny+WvvyEjPS1g7uL+r/K7E93g5wPJABvpUmsw+efrC9fdmKNKLzB4WL7gXZi8eEncjhSLgHMATwJLhMLfiEfdpqtVl0icmXnztIniXMR5RXpo9iOZFpeEJYMkgm/HI5tGOd/7cG7eR4oF1ph6ki+U9o/SPwP/2coAKQzbdZ9jdHz565fr1q2+jl55pl9zTCnQIVqyotBy8EFBZgPoM6vSZdPLF12Zuzc7hD8Sjww7EMyQbuSgD94uDhOcJoOyQNk8mT+QfP3Xp7NkLGJTFtBspnoz2zAJzsSzwPEB5QeGUqc8Q98kjR6+8+ea1GdFlhz9oAL5esC5oX0byCfBBXg5QHqTI31OFHqE+nXrx9XduYfi1AJPP9k6s47nUtBf5d54HuDdwvY5tHo05x06dOn6a3b2gXPh6LCTpS0z84vBCwN1D5x7teMkj5y5duXKBG3Ng8KCflma/XXEsoy68MYF3A2n0FOnTqcMvvz7z3sx70t9L8g2Ik8zLlQjOATwBlAjD3cPmpyZOHDvyKg/KAu2iVicopyeW8hyXhmXTyNycd11ACTAiPRpzyN1fPn+Bs3tJPhkSjAm1akGlHJ51T1gSTdC39jxAUZhGn05PHT56/vrM9Znbs4J0dvgS8oSWGRUXgSeAQmCbT4L2dCY9MTF15OWrokIPZw/mLYG+UvQvAej3eAKwAcweJp88dvzSpbMX3rZ02ZGbB/cI+Yj2yxe9ywKqqHgCyEcqNYFumzevX3vnPUk8M8/WDuLl6bPCkUJAHPMEkI/U5IVbXK+Dx+fB95J6sOxsk18Id+cAqNjZtYSnJnF5rR7o2dPL7trqYh+6dqkAwDziPEbgyl0WpFIsAGbf5LwcdbsVB/cJQNTrKLVPTyDD/9PD6XwfwB4AxLMCqhnIAdzQG8i+HsSjjz6TSU2eOHXi2OnXb1N2fyadbwGp6Wtk//IcORyL/IzqTwJ15sE9+fsjRy5dvnz+ItrxOMObO5OyEcDktaq3fQH6mVUsAB5/yy335O8zyaOvX5+ZmbmBC63ogfHXkMDZggJwgQKqsRpoenvwnklPjZ+YfPG1a6Iph82e03pZsyMB2IUAygFc4gGqSgBmnCekUq+cvHT+0hvXxDxZxDsqdUjtBbcyySvkAaCTpcSyya06BCDG3KOvDtwfPnzm8vXr12fkfEmgnKvxrACYv2Hd8ABT+ScgM3nRFREAp8TxtQDh6zOZ9Hg6PZ5KvnzxfbL22bnsrAjyYF0MzGHXv5DWrH0SiFpAtTX62MOZ7QBGmCejh9lPHj956fjZC1dFkGd/z512zHge6SZgAF4O4CwBEPOc23Nmn04deeX8m2++ee3GbXApLq6Ulk4E8lP+0gLIZs8UbAhygwLoFDlHALB4GDzl9uPp8cMvnr/KM18z71hI3ok3PMRqEcAD2OQAEIBbIsBK9wDC22OyHFCfmjx24uSpM2fExXXs6Yl4GCsRDwkwbXdAXYEcwD0hYAXXAkA85kmCyRMwg8KVK9fMma9FisfEE++ip+YOSeMcwKY3aHryojuSQJyAFSgATvDQiENGT7l96sjRazzyWjbmSN6F2RNL92Sr9n0BS98OsFxYObUA+HqR2hPt9JicOnHixLGX+Tob1OiIdSyZdOaevz7/iLsHfWShhqB7/3AnAB5g+dsBwLye2k/A4l+5xAOvzZF4YF9ST7QId18GoIWgkADuya84B8vsAYTJc34HZ58+jA6b6zMzzDgTb9g8EyIW/M3LARJA4XYAN3iAZcoBDG+PiXLS6anxiYmJqRdff0dcagGzBPPcfgfKKxiN6T+csUkCPQ9QBPckAOnsKcObhM1PTR47eenSudcv8pUW4oFQz/4e7MhvWTHQ/7JrCJpEDuAKASyhBxA2LxpyONCffvPN61dnRK2OqAfvzD5sj07+klgg/b+zk4U8gDtcwBIIwPD1iPPj6dRhjMUiCOo5yFsCvXgQN+L7VRT0j21zgIxbQgBOQKUEoDt7ST3V6k5eOnnmDZnaGyavR3q05OCcL/Fpz86dKeAB3BECKjImUCZ4mfQkcU/pXer4+TffvHLtbQR6o06vWz2zboHcWqKzX8ADpNASuOCLVSeIhfIKIDVJFp9JTyG3H08fOfz61fffv4EmPDgbmeJZiC9+jpeAAfIArq4FEB9lFYCo1k2dOnXq2Gt8NS2zzvRL2vFX5NQu7VmHKgvlAEW/ZrUAJ6C8Ahi/dPnyhasYi8XMg3imHs+7qdFXmoRswZbACrY+rCSU2QOkx/XcnsnnB9s9/hX/w2JY+lNOOi00IER+6ypH+T0Aky8AJ3rvJ7GiNJBCCw0IoS/vAtAJKLMH0PmXzK3ws0geqoAH4J9Q/Si3AKYgAHyu+Pg8rLSTWiAJFDmAGxRAeVl5PUDaWSeO7Nx+QAhGBLkA5ADKHwJWutu3gkOAvQdwRwgod1+AyAHkR698wADOTBXIAZwk5LsGPEAZRwQlUxMiB3AO3D4msMxTxcIDOCoHgAfIPwHTSxkClvV0lbsWwB7ASQIo7AFckQNQElz+HMBJJ65IEkgnRx7kMNzR1y5zDvCzSdkO4JQEigzA5aOCK5EDyI++IyzP2UYtoPC1gS5QAE5AeXOA8Vln1QKy2cItgfKQ6kaZcwAKAY4yHNQCbEIA1wLkIVWNsnuAdPlrAZUlgjxAwRFB7nAB5a8F3E0IWKZzzTlAwVqAPKiqUZkcwEmnzt3tAITyewAnnTj2APn14IxbRgWXPQeYJA/gsCzwTHpSfnkT7vEAZR8PcJc5wDLB9TlAFtXAcrYEpqga6KQYQAZQSADuqAWQCbjZA3AOYDtTqFs8QNlrAZXqDawQGwWHhLmmHYA8QH4OVBSLJIEOzAFsRwQtoQdYTqGV2wOkx2dxmW8FUCkXUGREkFs8QHkFgNsxyM92AArXAlxCf7k9wOQECUB8NC9XOFALKlwLkAdVOcosgPFbTnIAcAEF2wGcoeF7RAVyAGk6TvEA3niAMgvAce0A3qDQcgoghRDgoDNHv9/lOQCFgHK3AzjpzGFUcIErg0gc8qBqBmVsZe0LSFMtwFEhoFg7gDymqlHuEMBJoPxsBwDVYNsQwDeNWjIU+FdL8Q3KXQtw4Khgd/cFlNsDTKElUH62E1CgFpBxzwwhFWgHcJYCirQDuEAB2XLXArgaKD/cCSjSDiCPqHJQNaisHgB9AU7zAAVnC5eHVDfKHgJuOaMRWAC1gIIewBUhwPU5gOtnCClzbyBqAQ7LAeySQL5fgDykulFuD8DXBcjPdgTm5gu3A8hDqhvZstcCnHTm0BlmN0fQFLcDuEABZc8BuCXQSSeu8BQxrokB5a4F3OWJW57TXbQWII+palQiB+Ak0Blnj0cE2c0RhM4gzwPYY1EPUCW1AK8doAAW8QC3ndUUPG+bBHq1gCJYxAM4TAD29wvgdgBXKKDcfQFOGw+AJHDc1R6g7E3BDhsPYH/LGL538JIlsst4wuj3l7k30GHtABwC7D2AS9oByp4EOm1EkG1TsOgLcIEC0BRaXgFM3HZWDmDfFOyaHAANIeXOAegj5aevfKAaXLAzSB5T3Sh3O8CUwzwASaCgANxRDSh7S+BtyqvkZzsAhTzAlNcXUBCLJIHOaggiD1D4fgFuUEC55wmEAJzkAAp4gLRbcgAeFl5OAaSRAzjp1BW+LsDLAQqguADSTusLsPUAojdQHuNMlPjty14LcFgSSOep4JVBDldAaUBDUJl7Ax1VCSjiAdxAP5+A8iaBTssBCo8HcIcCyp0DIAQ46cSRAdiFgEnv6uDCKB4CHNcSWOS+gS5RQNlrAQ46bwiB3mzh5RQA9wUYZ84Bp7DYLGHu8ADl7g2sihyABOCsFu27RtlzAKoGOssDFOkNlIdUNdAOUE4BOKwziNsBbOYJzEy5JATQCSj3DCGOagiiM1B4QIg7PED5Q4DT+gIK5wBuUEC5PQDaAeYdpQD7HMC7NrAwigpgavy2k/gv1g7ghYACKJ4DpJ11ZRCdgMI5gAsUUP4BIc7qDSyYA0y5py+gvDnA1Pg7ThsRVMgDuCMGlLsdIDX+jpPOm8gB8tsBcG2gKxxA2T1AZoI8gPxsR8D17QBlbwl8uxpyAFELcIEC4ALLHQKclgMU6g10RwyAB5iSv7pEFBVAmgTgoBMHA7DrC5jMuOfOofPl9QDIARzlAVw+HqDcISDjLA9QKAfAtYFeElgARQXA7QDysx2BQjnARbd0BpEAMvJXl4jFkkDHjQcoWAuQB1UzcALK6gGQBDrMA9heF0AhwB21AAqC5Q0BE287ynTYAxSYJ9Al4wEq4AGcdOIK1gJWwCWOS/EFMD9Aea8NdFQIQAgsVAuQh1Q5yj8mkKqBDvMABa8NdEEIKHsSiKZgZ/Hv7lpA2T0AGoIcNSas4F3Dsi4ZEVJmD4CGIAedOCK5cG+gPKaqQb+fPEB+NagYiocAp/UFePcMIg9QRgGgFiA/2REoUAuYdNc8gWUUwKSzqoFwgQXaAdyRBIpRwWX2AE46c0UEQK/Jg6oY2XKHgLJXAytLAnE8V9V3D1/8N5RZAFQLqIprA6fQFOwGD1DuHMBxfQFz2bMZew9QHbWAxX4EKaDMSeDbVZIEusH+8fvLLABcF+CgU4ffX7gp2A0SKLsAqqQdYImTwGWTGvFf7hBAOYCzYkB15wCLArOElTkJdNCJgwHYeQCEgGW0yyVERTyAk04c5QB2HsBdM4S41wMUbAdY4hxg2VD2HAC9gY46cd4dQ8rtARzVDsA5QCb/93MO4HkAexTPAZx3bWCBu4e7oykYCvByAPtagDsCQLlHBKEW4Kgz580VXAEP4JwkACGwUFMwvSiPqmaUOwdw3ixhlAS62QNUZESQ/GgnoEAOIJJAeUw1g+q67s4BKAYUumuYW5oByu8BnFSBJgEUqAXANuRBVYzy1wKc1Q5AHNv3BXgeoDCKCsCB1wba5gBuuWMInYDy5wBOUkCBEAAP4IokECeg3DmAs0YFF8kB5CHVjXKHAJ4fQH62A4AcoJAHcEkIqEBLoKMU4I0HKLMHQHewk85cwRFBLukNpBNQdg/gJAcADzBhmwO4qBpoMyCiGIoKwGnzA5ACXN0bWPaLQ1ELcNKJK1ALELOEuUABlASXtx3AYb2B+P1n0vnz5LmnHaASOYCj2gEKTxHjoplCy5kDOCsJRHe4m6uBSAHKKwCeH8BBIQC1ABsBuGZMIJ2B8uYA8ABOCgF0AmxHBLmlHaACDUGO6w0sfHm4PKaqUe7eQG4IclZvkDcmsKwCSDsqBMADFqoF0IvyqCoGnYAKeAD54Y7AnO21gZggwiVZYPlrAU7ynZQDF24JdIUAyu0BnFYLIAHYhgAeEiaPqWpQDDxW9hDgJA9g3xvomhwAPrCsHsCJM4S42QPAAsqdBDpuplCbC0NEO4ArFEACSB+WP7s0VFUOQCZQoBropBbte4E3IqhgZ5A8xgmg7yq+rt2Xtu4TB0rfxqXyhwBntQQWGxUsj7g3UCTBqAOcdFqLPbTNTBT+FzhAP418FBb63Zj4E3EIf7ZYEcQ+uZvBhwrQS/THC+LHXJdbANwXUPBnrTiwByg0JhDnW54+4ycxLbQpXmMbEvsFmFQczEcZHyCW5qdRic89vU7/RjwMdrCPj+WXaQcfg52WPeS58cBuURbvxS79M4wP1Yt8LP/pay6WvxqIHy/OCi95xedKgkryYTmvFmA3zpm+wA570PeXC+N0it+Hn8w78SLv4f0SvJPW8PJztqOC09NoCeT3iz/+SMyByqdT7BG7xH4dYosPke8Se/h9VMQW9hsvW17JXelFvQTIl8SGeCdBbvJL+oaJvB1WzM7N3bpVVg/ASaBgQSpUP336lijTn9hh7BeHYz8gVzgIC71Mf3gvlnhYT58sUVkcJZZc4JJ4n9jFO3g/oVBfgPg8XvDB/MaF4F18FP4fH8X/NgeF3pwD43UiZXbu9u3bs/S8ffuWUbp9+wYwM3PxAv1dvHANKxQuXsCD8MaFy1euiIcBY1PfKde8unzlMsHmhhlFsbgA+CfzWdHPnmAjf8vcq5PC54EWosRL8bJxLJ9nXhhnLXdlwtxhlPKOsRdA6tot+bIOvJGe/GXEg4iaZXLevpqPixcvvnHxjTfeOH2UgIV8igfj+MlTJwFensIfL3i1AHLHiePHTh07Nj09SX8CKV5O0o7J5OR0MlUYmXSaHgBK4plKZ+gVm5tnF8ViIUCeOf0kmWBpm3/mgv5uzc7Sk/6E1m+/L57vc+EG76LV+/qTHjqoJDYsS7FP7CiMG+/dmLkx885pGwFk0snDSXrQ32E8qTAxMZHmJ/5oPZ6mQnqcV1NTE1OZqYlMeorKaXpM0NmlPZkpOs3izGfE6ceCivSSBG8RD1wkSjKZVJqISaemiLKpydR0OjU5maL9zCKtJ0VpAYj65CRW/McLkrG5wdtlQnEBpC+/WQhwN/Y4j+f58+fwOHqkKF48chjPF5J0Jqf4nBJwkgHaYezCXuwnlvDMYC1ApQlxnGAwZeMC6eyDE5DCK5x6OpB4wJ94iL1ECCgxaDH5ESVYJejRS1wQlOBx55DfcPlQPATAMsbJEgBakrEIDgjj6fGpcXqIxQQKKFIBB4EKYT04VtgFPWgXb4hNIoXtIz1JD3qmyFBwoqdSaSKCy+lJXk/y+acDaIVSJkV7qEAfQSWyKvESSLULgXyqmZ+7IsmE/LxqQlEBkAJAYnoKLoxOMhyZfBAzOPVyQeCTbwM66cJI5B+binWBP/nvPCw9igvAQ9XDE4DL4QnA5fAE4HJ4AnA5PAG4HJ4AXA5PAC6HJwCXwxOAy+EJwOXwBOByeAJwOYoLAJ3eJkQXuPHgP3OVs8EL+SEeVjKKCiCFgRiyF38K3cK0zb38eGSmMimMxEhN8RFiQIU+GIbKGKA0rXfgT7OCCEbBBnrPci7yZMcLfSW/qYe7RVEBTE6M22NifKLQSwL0qj7QSozeGcdgEn08CQZi4TFOwhELPOWSFuLBeqNHLkhePKKEdQa9QWFyAanJr+6hRBQVQGb86i3CLD+4wKP5eDjr2xdfL4DXXn8NePX08eMn6Y8XvDIfYoHhk5ew4KUo6SuJUydscQx/x45NTWGoUGYanmaSHMj0JPkiG6fAnmRR2DsgK4q5LxvIYUQVwmGx4NGO8oEd8ieXjKICSI9f5QGgGA+a5bHBGL07n52dwxB8MbqbYZb5YF4B81jN86UxYhAwrwFa8qG8JTa4xMfQ7ltz0Nzt22/PAMYShbdn3nn77bevXn376tsXr1ww/sTqFbtRwXAjGbgc4U8wEo2fYlvu1JcYiihexNIY70lAiMuH9YgcCA8lHJNciXi4ENiXv9/uyJIgf3WJKC6ANC4NA0FyjD8K9MdC4C1JoiCNd9DreJl2QCxiif1UEvtwFLb1d2AtjxBb5po/ITs3S59Jj1lcZjJPK3w8v0UIkY8Rb7k1d9RuVPDU6dNnzp45c/rs2bO0OHPmDK2xg7Z5iQ0uGkCZ9omN08bztImjrx7F6uXTLx99FQ+GXEno9ikXXBAbYi1Xxmu5D33nYV6Yeyx/coyzsQLKKwBxYQgbMZ17Ot0StAfX+OAyD7Fhgsjh3XiFD114QC6IvHzInSQZfBr+D9bCCekfxt8GUiAw+1jPzZ7OvzQsmT71PmTCcirw4KdY5BxmLYtNC2blGq/x14B35MNyDjU29AKv5UbOPgaVsJH/Qkm49er0nSmgqAB4smjm8I7BNos/VgI+gfgUnwQ+6XSJpQV0FiWd+gJH4HNoU7xPfg6/RhtmiZc4WafzLw1LZU7dphPJ78PHiu8FrmRBFPkTcEjeK/wv6cP5j16Xn0FL3sYeXvODXsGrYjf2oITPFm8UBeMfCh+HfbwErG8V2+YTL9GC3yyL/AKt8EFQwKvlvF9AhS8Pz9cAQLtoPx6LQhzD7xCl7JzNhSHkASAAQQyfdyyMApb0GXiFHswriU7u5zW/IL+q+S5jIV4AzBfxE3iNLXrKnSDJOF5+OkriJfP7iZ3ij/foT/3jxVJAL9MaArCJgcWwnAIQEpAMUkE8sHF3oFNQSAB3/Zk2sPko/gWiYIC9Bv8w+etYXLwJonk3gfcSr/waSmIXjseTd/FuLPgouVcyz58ly7Ra3AMkKU+01BWKCuBe7xxa4lvNw+7hfwH0+wt5gHv8ZAcAv5AU8OpUcQEkp5PfsmqkqAAyFb1jSPk/mezARgApDgHykIpi2VSm/2N4gEVCQCr5W79lrSksGgKW5tSVCQU8wEnyAEvzM5ZNAgz673OvFq8HplK/0/PoS6UL4G0n+U5EQptaQDJFHkAeUlEsuwOg0tyrxSYISKYyv/zZ8KPfzMhtwmIh4J4cwJKfEVsPwCFgyb7KshoMcoBiEwQkU38xEA5H/6JUD8BzBcvPdgIKeIBMeWsBKw7mb0MOUCQEpDIvPBqNRsP/bakC4Gqgc04dKtOFagEuqAYA2WwRASQz3/rDaCwcjfwzi5UUF0DaaTOFFqgF3Kpe/nN/WDEPkMp861/2kAOIRj9raS4uHgLu+c6hS3zeyQPY9gW4oR2AQR6gYENQ5qXfJfL7Y9FIX6kCcGItoEAIkIdUHXLp4ZZAew+QSk1/NhaLxmL9FASmzclOFs0Bls0D3M1b7XOAFNoB5BFVDvIA9tXAVOqF3wqTA4gRIuFfM93Eoh7A+TmACAFQQPWpYOEvQkugXQiYTr30m8Q/6I9F+8N/kDTOUlEByIkinYJitQCXeAASgI0HSKYyv9ii2z8pINxlZoqLhQBH1QLJBZwetxWAoyozdw/6ma/mj5ROpqZfeqhb8h+ORaPh7t822gKLCwC1APnZDgC6Q4uGgOoH5QB5J4Ds/5Mf0e2/u2uQFND98dI8gBNbAvMFkEpVeUugBXbtAJnUb4RQ/wf/sQ6swuF/WpoAlvWOIXdBWREP4I4QQCawQABk/smPNYQj4H2Qnq307I+EP20ctVgO4CQPQPzb5QDV3RKYg7wxganp5G9/ukn3/9FYTwdW/eH//JvT8ohFBeAoBRSpBbhCAZQFWXMAXD/3sQ836/yTB+jqonV/f6Tjz0vyAJmKtQRW4FPpI+n3FxKAPKjKge7gSd0DYPDfNx8Idkf6pf+PxqItG6GEaGTdIyUJoJo8gDykupGdN4eEEf+HP7Yq1B2R6R8kEFkbRikaXveJkgQw5bi+gHn7zqBb5AGqTwJ5vwhJkN4SmMpkfvuDvmYj/SdEY93N/Vj1Rzs+WZoHmOAk0DGnrkgtoProtwWFAE4Ck6nJ1AO++ja9+RcgDxBCCkAS6O/6ef08VVkIKDAeYAlaApf4NNn/O3iAqSQ5/8w3P/FhMv+wST/xHw0HesgDoB7Y/hG9xXhxAcjPdgC4GmjvAaq/KVgogscEUvL3yAd99R2gXygALQDE+7r1zD+V2u/XGwKKCwBXB/MH3zGWw29QCpQtMCDELbVA5ACpzD/+4H1Ko9n5I+iPxXoC3A5I/FPxl2WfwaIeYN5ZLqBQDuCSJABjAl/61CpfEJ1/SPfAvi6AroZ+2kGIRiKhR0oVgJO6AxECbFsCXZIE0gmYfflX7/fVI/kH04PSB7AIomvX0oLV0B8OvVCqAJwUPIt4AHlEFQOXjs7/xy/9o9raQBdbP9OuWz+R3qN26jlBLBz6BZkEFBWAk3oD8T0hgALtAPwzqtkNZLPZ2R//i3pFUbnuxwqQ7ItVJBAK98skMBpu/PB0qR7AQWetiAeo8iyQft7sjx5/uF5R13ZFONDnkA90q83SK5A2Io2rZKdRcQGIhiDHgHIAm1vHVn8OgBkCfvylNYqihNrR1ivtHDAE0N+sdhv7o5F1q0oJAZwEyn/iBJAHsBGA8ADykKoDuX6y/h9+0a+oSrCrX6/6MfXMPi+iVPEL6QGANqNtq2R3UDWFAOK/UA6AhqCq1ACmD/npd7+8RvGrDU0b+w2Odcs3PECTKpqBeVd/tM33khgWWFwAuDTMUS7AZX0B9LPmZn/wuTVKvRJs2hjrj0Qs3t8knxAOBtAIIHZR7bDN92cleAA5S5hjIEKASG5MLFkOsJQi0//X7N8+SJm/oq4DsdFIsyB4EPU/K//9IaVLVgF5N3mAUgRAIcBRjeiiFrBwttTqvDII84nNvvvWF/xEf7C5mwf9xSIhMEzcM/2mBqLtiugHkjv6ox21clxoteUAZybyPEAVhgBkfnPzP/zKr/vrlVq1uRukDsa2bdnRHN62c+euHTt3btmyTZKN1caQss7gnxYIAZ8qJQeYuJdLw5b+nIsQIL+8geqrBqJVY+7v//Vqdv7N3Oe7dWcCaOs8sH//gQMH9h/YdWDXVimBWKRLVVkkuguIxsK1JQnAadVA8gA2M4RUlQBg/NnszR8/1qAo9aq/uXtwcNv2vQltTNNGtURTRxz8C+zcxGyj4VftsmaHpIBo7afEfHJFBbCs1wXcDQo1BZMAqkMBMP3s/E/f+uJqGL/S2rcZ5BPGRsfGRrWxxpa9+w4kpAB27RL2HlmrBkSOAAfA+6Jh5dPf5DNVTR5A5gDyyxvgEUFVwT/F/bn57M1vP+ivr1X8SuuQIJ/oZ/apEGzacWCf5J8UwKRH2lWlTToAPSj0R5QPfYtjwOJJoPznjkDhlsCqiAGw/5+8tbpWJeNvaB0A+2T4ACSAEFDXvJOpH+XlTnAd6QmqIR4MLMAaiERqP1SCB3DYtYHwAAVDgDzGqWDbn7v5t48/rKi1am2o86vxBAL/KJs/g+QwfF8TC4CDQPwA5wDhJlVpJ5tHGeQLJxD23f/S4jkAewBHNQQU6QtwtASQ+M3P/t3n1ii1FPwbevdQxg/Xz5Yv+B8bS4ztvq+FBED0swI4BehvV5S10QURgGoBvvtfXNwDOK4WQAKw9wCOzAHkd6YVBnvc/LuHqdJPqV/w0REYP4V9wfvYQblOJLp9LaISwALYBq43NqhBBACde4mwsqpEAThKAbaDQh3eDsDGP/fuX35GRd7vD3XujovUT7B+SKwImhZv9HXspxxQVAPgAKL9TUo9qoD9tAENyBVVA2vFtSGLCcBJpsO1APsQ4Nhh4VmqwGZnf/TYg5T31ypqYOAJDv269evGD2iJ4fqaHrMOAAcQbVOVRlkFJEgJoBbgq30kjbNTXAD3PE/gEqNwO4AjBSBvFfGjL9WT7VPuX9/Lzh+x3wj8JIFDQgZaYrOvbujALukBdhLT0W7SjRwIxsTzAoAAFvcA9zpZ9FJDtAMs7AxybDsAMv/Zn771RbT4kvWHep9IaJz66QD5eiJA/Cc6V9XtEA1BiQP7iOVoT0Ct15sAAME/lhHFJ64QXzwHkN/GEeBLw6qjMwiuf37+3b/8HNJ+qvq19O3h2M9kG6wTZBSgCmG88b4Q8Q/s24cAEGlUlGYxRMAwfVGIRhpLFYCDzhzSJQoBed3BDvQA+Cnz2Xf/h9VMv6K2Dgn2Teu3xn9OBBPacM19vQf2iWoAJwDEf6A7Jq8GAfW6DAZjkXWlCAB9AU6qQHM1MGMnAIelMsDN7/9rNPgT+w0PDaDWj8ZeXQF67s/hX/gDLdFxX80O4QB2oRE40qQo/nY5RshgXywj0ZIEwB7ASS6AawF2OYDOvwN+jLgJ2E/e+uIatv7aQMfQCNf7csyfSD8kfYBYaomRuvsadwoBIAGMtQeV+qYI822MEGH+8SzNAziwHcB2QMhJB10ZBOOf/+lfPSysXwn0mqFfIzfPZDNGdTfAq1Et0XdfTfsuFsDOTVTP6wlSAhAm+yfyY5u27dq1a5PePUzVwGhbzZ/zVBLFBeCs6wK4LyBtzJGjA/MErvyfwV8Q7M/N/uQra1DvI+cf6BiG82eesRwawXrUCP+0lkVNG2m8r27zvn2kgH1bKf63NyhKsEc4gMEtu/bv339gFwtAqCDS5vvNEgTgrCQQJ7BgCHDA70DiL8Z4A2o91ftQ7QPn0vIHhrlANk8PUK/nAuQAhnyrmrbBAewk/mM9IUWp6+IWoMFtu+AWdkEA8P5AJLrB97vcZrZ4CJDfzgkQOYBdNdAB/FPsn5+/+Z3PrcYwT0JrH1s/88/QtETnsEj4iHuzJniQVECvUQrYs4UcAOw/FllLCmrjccCDO+EVGFsRDQSiAd9nSxSAk1wA9wbaCWCF/gzTuhD552bfepC5pwAQGGL2JffCz2uJDXtIDdLpcwWAy9BIIl5T00hc7zpAHEfDZP9Kk2gA0FsGyQfIHABHRBTfZ/nisEUE4LRZwubO2rcErvCfAfpnf/iXDyv1aPVTAi1f3Qffz03+UgPYGFk/bGzmAA5gVU3P1n0HdrH/D4B/9v9b5RBBjBDB+BAjBii+j/DwycWTQEd5AOQA8ssbWNqWwDv+Rwj8RP8PHhPVPkrdeofiWiJBVDPZXOFjlhO714+IfbIGKH0BWgG3kwOIbdlH8b8/1t9In9KMHgDK/nT3DwdA7OvXCoRV30emqjQHkF/eAAng/RUsY77C4+9+n0yfrb+hbyQB9nOq/Qj4mjbaGRoWY8D0KMDxn4AMwNcd24UG4Eg77L+RK4Bb5OgAMTzArAUKD1BCCHBcbyB5ADnxgYml9QB35ALQ6DM//+5bnwH1wPpe2ehjAy0eWDuivyR7AFkK5AB21/uaY9s4/+8G/wFMCTtoDg8j7GLblyEgUpoAHDgm0CYJpBzgxsocD4D4Ovf9r6Cvn9HSt0cm/lbzlx1+mjbk7xD8665fFkY1raOmpmcQ1wFEmf9QDyUAm8j96wFgFJUDjgASJXoACGC5FHA3/3cue9bm2sCVmQSSJCn4//Ax2eSn1LY8EafYP0pO3sI+USxYJl10+jvRISBSAkMEohuopj2KOl6kPUgfFdwYiw5u5UuEyAEgAOwTrcMMFCLhkgXgqBwgO0cCsPEAK0kA8puQYWVv/uBLHPcJepufhXsB2dSjjSVGWv19OcHBSAASzfc1xjAxUHQdPiuI+L9VWr+MADxC3HQA7AFKagdw0vwA5E/hAeSXN8C3j18JP8P8CnD98z/568/p1r/+Ufh+DPEmgpljWoxaenuoDpgYCviH9PTgoC4MlsaQr458fjQaZv5DPUTwNsE76Kfnrp16E5CoBURKzAE4CZTf+c6x9Kec1Hpmwrgflg72APKIlQFU/G7+Tw/Xo72fEBgQHT4W69a40Z8hREDi6FUDcZ1+Xhx8EtLQxuIP1bRFCZFGfGCgJ9Y/uMMyOBgRANmhFZEmEkCJ1UDneACKq3YhgDzAjRUVyTDQ639dzSP8FcUfGqDUPsGJnqScKnzx3aJIEKae0BIhdQOCBEOkARACHTxU3wj+e0I++rwmyv9F+g/mRQVwF9UOTe+PDKCtUaktoSHIgXcNO5OetEkC318Gd2QPGP/cu195iMmnWn/HABu/dbAHhDA0oG+IOgAdMqCqfcYR7ANYBXAAdTD/NqR/SnOY0n/BP8CXiO0TowEMhNtCTRsV32dLaAl0mAeg0GqfBN6gX7Eifgd9j7mfPv6g7O9p6N0dh+c3uBfuntK6liHeJbeppp9IrFcD+0kptKW3AQDEf19dN5l/I/PfRvyLzj+yf3GBIFqHc+hvDwXbwt0+5Xd5xvhFBeAo/m1DALcDrIifAfOf/cFqtbYW7j/YOywiv6jnG6A9Q4EnhCREHkj+ITGkWiIAIFSgacN1nVGq/cP9K21EMLf+U+UP3CMIHNiWY//hOjXYHY60+Xz/srTeQAcJAAo4a3NdwBR7gOUFchD6DrPf/aII/er6PtCPFn9p/qZZa1pLC8b+WPfEW9TggMG//gptJzrbo+G2OnxmoD2qh3+mHhrYh/hvINK+LhhcF47E+kkAf85zhS4eAsQPcADIy6M3cFJ+eQMrxAPA+n/45TXsqdVQ3zDGeoxyw44BVOyFtfdadyMD2BNSQ9uppij3kGdAFYBe2dET7absj2SF6t82s/NHBACT/0gsvG5tndrYTvxH+ttKuy4AvYHOUQBO8tlMgRxgmRWA0T7z/16M9VHWDOAKHwv5xKVRrx/T4hvUHbqxC1vXEr2q2raF+KZ4wWFBDAce1RKbwy1s/grGf8rOPxkACIJ/YjwWa2+qU+hD0EnYH4t0+Gqqb1Qw9wWM2zUF31huFcP8f/w/KwpF6vpAJ3f4sAPPAZNNNcInAuvN0Z8kDDp4JKA2xOJyFwMNxlpiZLC9kaN/sCMSG9xuNP7J/G/nZmH8kXB7s6qqwSayfkapHsBhtQCKAXbtABDA8v4MmP+3ebRPbUPvE1TxI1KtqR+xzG17JAFiu0NFtNcMpzCqaZ2q2r1VqkI6BToyMRxdxyFFaezuj23dK1iX2L9//xaMCYtGetqaAyqFiKaNbP3wCNF1vvtK9QDyNzgBnAPYhwB5xLIAnb4/+QJf3qusH5K9/RJCBoJTxqi2R21Ary8dIl4E0X5lbf9Oyz4WQGK4K0Af6VOCmCpu2360/hvWvx/dP1Ey/vbGIGIEVf3I+4N+OIBIo89XytXBzhIAZYF2fQEptATKQ5YFc/Nz332YDTXUKwf5a6N79hoisAqA2G71U31PboJoSgrIAbQPco1Bmr82mtDiQ8L7K8Eu0fhjzg9G5b0YGxLuFs0DwUBX2GAfiDTWlnJ1MLcEOkkBaAewrQXwkNvlAWnv5rf5Gr/6jj2c+jOtZlOfsQK5mrY74BcRQJB9cCyR2BOoXRvZxm4DeqCQMJqI724R3j/YhOzfSP7j+w7sI+wY3NjdtRZjA5T6UFMXYr+F//5IyFf7CJ+pKssBbK8MggdYrl9B9jN3ky/w5twfnf3gcEzrZI4PjY3Kjj1mm6qAiU41NIyDRoUyaBclBUp3bJ+oNPDbKfvrw8BfQqibvP/OXbB/ArO/c++Wwfa1DYj7pI+1VO+TqZ+Ofgig5Cli5C9xAlALsL0wZNkEAP7/Xrr/PQmiUCdR6+CSCOl6XMcrwwG1g6KEuWss8URQWRvbiuM59R9NJOIDgVofVFW/LhqNbcfVADr7e/ft3NLRgCuLVKW+PtAdieZMIc+9Qv39G4MlTxLlJAEgB7C5PHzqxI3lGtZA/P975j/QOyLZh61Tva6VQ7qAnu4T2VThb9jDzl6GhDFtZL3aGBncB9UAicQTAw/Vsk+pxzTRW7cQ8bvg9gnDmwc6W1VMJEdxv7m9O8a3jjcdgGgTjsa662pKFICjUoBCtYAThgdY0l+D7H/2cR7tTck/820Y9p4AyJU4iP1Md2IgqG4g+zdeSowlBtRge4zqgNhJ9McffUgfR9AWFQO/9+1CCNi7vbejVfh9RQ1s6O6JmJMDSYB/PPu76333v7SoAJLOawm0vTJocplCAP3P2X8B+pUWVP0PPfPcM4JVMuOvNggzF7090gVoWrxV9UsHgH0wenIAbbHYXk78tUS8s4EZRu5PoX3brv37du4kDeztawmoBEwjqTTTS+T6ydL7+eowYfg6+wTMHVTKTKFOSwKFB5Bf3gDlADPygKXGzceJLtXfEdcOPfMnzz//vC6AUa3Pb6nqcQJI0LShgNoSh7PXd2qJ3iDuAnFASyDz7w3KcSSB5p5IbOvOXfv379w+NNC7npgH+8HQ+nXd/XzrIHb+VkjygUi74vvgN6dxdhYNAQ5yACRV+5bA48syImhu/qdfJrZqG/oSxP/zz//D8//wjGCV6nFrQ0QzBwSydN4La090+BsGxOgggHYlhtQQBfq9iURimIycyUfVj5K7TVv27t080NsR8CPhU9W1zeu6uiOU4RPDlrzPsH6rC+jwlXbDCLQDyJ/jBHA7QN6FIdYcYOkwl83+9ItoggvsJv6f+wfC839iuPpEgCI9XIBu/ASSxR6/GhoRLzAoJoSC3eTpE/E9vQ1yGAnFfgrvm3Zu6dsQaBBuv7mpORxGxIfTl5BUixUtuSC2+iNtSskCWMYmlDsHtwTmdwYtgwAoeZ79MqXqteuHNe0QmT8EICMA23WvUdMzNIBOfz9lizowFLgv2E6hfvtAq2DfR9bf3B0ObxzY0OBX1UCgYW1z80Z9LvDBwcFNm+gB6JwLynPRH232+X5VxMqiAnBYS2CxWsBSh4Bs9uaXccEP8/+MsH/JP1l6ok/ttBi6fon/gKK0xjkBYGhjiSea10XC3V36EEJFCTW2rWtqbm5eG1q7oW1DOByODW4lbNsBxNEWTMECq53mQDA5IohXYl9/0Of7pRIE4LSJIikG2OYAx5b20jCMP5ybfYyrf5TSa0+xA3juKckruA6RB+AIIIMCmngSI1SDHxKyIO+AnCDe2tbTHhJNvvi4UDsx3hPuIy7J0Lft3bdv735iG1f/jDIO8vMgVqNbTMIXOIJolATwiyUIwHE5AAlg3K4WcGN2aX8G6e3fgbQ1w2j8/WPi/0+e16mGqY80cI8vQ0YAEkpfUG3ZJ+v7qCkkEgPNPNZX9vkg8d+0k943Snxr4JhB3BPjzDmB1geFAA5IH2DVAD2xCtf7Srtv4HK2A9w5ZWR3yAHsPMDS/gj6In9NButvJf6Jy6eeee4ZmD8kAHZHtSE/LvKhTbCPwT1EqhZfr/g367KgXZT3N1Pa7+P5ooKhdT3RwW37dVMnUL1QllgBYsnmjy1a7uQJwph2XosNQn93LYYE8tlZ3AM4yAVwLSBvokjKAWbQJ7d0mJt/azX57NYniE4m9BDI110AeYBev2WAn3ABlBco9R0jXDektyW0xHCnEfqDbd09VOs/YDJuQpi+oB62z0/WAMcAgk68oQI0A6xKcjPA4gJwUg5AlnfWbqbQ4zNLquNs9oe4sUsD8W/YM0MwTklgh9pKVFtBVUBV4cv/2ftT+B/Qm/ww2p8qdzst7EvSDcYljKI4QlwQKsCTQ+hKiDSSAHhMcHEBpCaddutY28vDuRYgj1gKzGVv/n69Uh/Yrdv/AqAnSG3lgSHGNZ7wCoraQztRpiMGWmWTX33jOqrlbd1yQPIu7TsPC/dRDiA8gP40FxFUAj4iQ2UxASTZAzgqBGQpCcyvBpIHWEIFZFEBqA18lcjUq/o62NtriScC/g7REqxngKOJPSG1FR3GBEr+WrjaT+E/1BWJxbbtROgX9OdjTK4JuFxQlCCUBUmggWiEBPAIXxtcggCcxD/nAHm1gCRygCVDNjv7bX+tqvQRkzzVgxSBfq03yB5S1YEc50DHPkr7MDUYvTzM9MMBNHeD/n1gH/Qv4F9wLRln7mVZHKxHABYAQgCevLFR8fkOl+ABUk7zAHT2bRqCRA4gj6g0KNegBKC24dGvE63MLTNsgZbAGN8hS18QRLGnQe0C/5T691LND+wHQ+2R2OCmnSBTd/sGwwIm+QcPHuIigbbwhgP6JaELPUB/pJtSgH9SQg4gQoD8ZU5AkVrAUiE7/9NfV+rVR7/+9CFimLJ5MbPfITgCfUYPbb0a2I5oTxAXemrxRmVtLEGID7Si1kfPxm5c6Empn0j+iFndARDDwtgF/wbzXBT7iP9tFuY5BeQFo83n+0BSesrFQ4BzPACuDbO7MGTq2JLlAHSyHifyHvras5JsTO+shwFZ39OG/epacemPYJ8wFAxs3EL875Ft/kqoO9If27qfmRf069wajPNKlvWXGGPwF7tsgr/YE401KzUf0m+yvVgIcFIzAFyAfV/A2/L1imMu+93V5AD+6NlvgFly97kX+QEJbbeqtsT1QT/QgDbSoqwbjCdG+oLc6qM2tEVjsc1I/EG+Je0nogXlgnGrJKyyGB3db/X+WOlJACGy1uf7DRkBFvEAzponkL4pksCFHuBn6alrS+QBstmbv6fU+vueffYbhyiwj2l9+vg+s9VfS7Soqh4BAJLCgBoI70wMtYB9Cv4tG6nipzt/pnUh75JtQwJiJffSmzBjnIX9HETCAZ/vE6UJwIE5QP6IoJ+lJ68tVQTI/pt6pfbRrz/7jWfhAMaGO+I5WeBBSgwS8ZAa0C/zAijzeyi0cdNIrxzuQd4fV3lrbPiG9RtKMMxel4FVA1iAf9AO5ulpxH9p/7FYe73P9/FSBCBqAfK3OQFUD6QcYGEI+FmKPMBS+LHs/NwP62vVAAWAb6ASoI1toAgAptHgI8b5U0X/iQa1eZORAnCcCHb3b24V9Adxl59tstUPnAKiQHwbli9LvJQ7hRDwtl0y/5cwmBeFaLfPJ68MJSwiAEfNFo6GoDNT+SEgk7m2JKkMBYAvUgD/AwoAlAKQZx9qeMJwACCbckHyAAOUAuw1QwAlhQ81b9wgzF9thPffJ8i3xH7DzgVMHRAM08eS3pjYkuf1CYYKcLMQ34dLEoDjagHsAXTfZgIeYAkcGf37t/yq8ujTEACZuxZvWS95NlqByNwx8r+bIoO+Z1TrbWqXl/k0oua/88BoAuQT+0SreIiFUbCsDU/A2/Qmc0oYLE3edUQilAJ8cLokD4DbxjnKBXAOkO8BliYEZOdnP1Nf63+S6IcHIAfgNy4ANMAdAYGo2UuAHWEx5ENp6u+PbYL5M6kmcgwem/IAXQumMsj+9SkhLSAVQAhSDGHF5/uUESiLewBn1QJghDbjAUQOUPGfQf/g23oAQCuApm1oJQewQAKjGOe/drsx8hcN/9L8A+3S+zOROq0MLgkrR1G8oFu9AXrrAU7/gEgk3NQsirlAX3DNx41UedEk0EH8oy/A5uLQn2WoFoApGiqM7M3VqhL62rOkABIAhvgOaEaoRy2QnpTx71GDXTv0SgDxvyfAc4YpTeH+TTsPjBGLOR5At35eyw2sDO51RSD+7zdmBI20d62tw6RxOVEAxcha8gD/TUkCcFoOAAXYtAMklyQE0D94TFH8X4UDIAGQ6XeE9giazXn9MPKvT/VHkQPSa7jO84kQj/gKbuiPbZUDPtjDs30bpm5AL1vWfBByhoSYERxXA7U3qWqI8kmGcP+6DpAC+KaNCXUX9QAOqgaSVu2qgRAAOYAKSyA795OHVfWhp5EAPP30Iart+VtkBND5P0hbaAYKDcZ5NBBtxXc38mWejeHo4BbQDz/OzOZCmLjQg74yC/yuxD5BcSTc3hZSg2vbeGqofITrfL4H9IbgEjyAkwRQYEwgPEDlXcDcX/lrG9AE8OzTYFvr9MtGAIYQASgPqO1b0fxPWtDifTzBo7ouHN2KTl9h/CCW12TeVutfAEE/kw/6KfmPRSPdXU3Mfk904ZVhwgVEIl0UAYxmoOICcOCYwOyZ8bw7hyaXoiEom519WFVavg7/D6a1PSH/sJEBmEh8VW2IYqwQHZOIP8qX+jW0R6nuB84hAcF9np0LJWBJ2+wMxPEgP4HpQKOxnq7GUINa39DYQ7HfuEKIedf9P2EdCeCXTCtZPAeQv9AR4AEh+QLIVLwWQJ/+N4q6+n/hBADkakMNqAMIUPYnPMColuj0h6KYKGiM7J8b/+pDG/sHRae/pF5QLrkWJVGAufNKmD1cRiJBj33bYz3dTQ24EEUNrQ0vMH6dfLEON/p8H5ajgYDFcgCnjQk8M5F/06hMuuI5QDZ7c42qtnAGgG4AhPo+PQKYl4Dz/g0xSgEoBuxpRddfoCs6KFp+mWKCJFsCW6OjVDkA57gYAE/0E2H0wOiBvTt2DPQ2hQJ8fWhD87ouXCEI618QAQwXEK5TfB8tUQDJSXgAJyUBtoNCk5MVzwFIXm8ptbVPchvAH1Oyp434/bjMG9Cr/ATavz7YGSX2tMTwejL/2rrezZv3MqHs0yW4SZfeyIau4yDJhJkfPcBef3jHcEdHaygU5CvD/aF1Xd24NNjCPFcKLN6fEMFwsI+aOWBVJYFcDbQbElbxHIAygM+pauuz3yABUGWfiO5T9TqABMcATYuvD0Rx/W9igFv/1M7Nm+PEaw7TC0Fks73zlX+YCmTf7pamlmbinaeDIPqDmAE4GhPzAoiWINkeJOnHiouRthqf75Mm/4uEALQEyt/oAJAd2s4Qwu0AFU4CfrhG8f/Rs4Sn2dWPBKgOAPoPmq0A6ApKfNW/bnM8kdAGAqj+NQ9s3k6V/wOjeBgGDrIBedVf4sDevXt3DG0eGtrc29LR0greoR08KeFvpJQfzIN867wAugRygRki5eQwAsUE4Lhbx4rxAPlJYLrCHoBO0l/V17eiCoAqIOI7rv3SB/0QRBpIht8b7MbQr04/+Gvq27YvDuIJ8AEYAoSp/jDhG5l6X09vb29fb09La2trcz3TDpunvBEl1d+0YV1bd3+EUn6q8FupF+RbBGCGgXa0AlhP0aIhwEkCIB9QqB2goh4gOz/3sOr/Q1QBRBuA1qniunC9+q9DG4u3NPRviyf66pX6+oaOwc17h3o7O3vpD+D1+oaGhiA96OkPqnWqSp6C7y5FBV0DytoNG7rJ50cjMHvR3GMIgHgXD14Q9Sb7sUhknc/n+5V0iQJAO4DDagF2fQGVbwrOzv+AsjD0Ajx7aAytwCOt/lY9BzQrgWPa6Ii/JbZtpK8B87h1bN4dj+/uI3SSiQNrg0E/Ue8n5gl+LAhKfVCtDwZCocA6Qnc0Eo5gDigK+VHO+BZmfQasW7IpOEJ1gFU5M+ovGgIc1RBgPz+AaAms3O8g7/J5Vel99tmv/zESAKrtm5f+5EBL7A62xXZ3klGrDV2bt8dHyVlQjTCRiCPYx/cMCPR1dW1oauky0NbV1h3GZBBR4p2Ip1TfMheMAUG49WoAi/ELdKs+38/ljJhYPAeQv9IBQG/g2Yn8lkAIAE01lUI2+/er64Nfe/brT48dIgWMagl5+TdXAIX1ixwg0RfsjrbUkwCCXf3beTIQcfUQPVF3YFDWd+DAlm1bt2/D3R4w0Sfye1oQ6/rMf/ns6/auq8CANQhE1lEd4BdyTGSxEOCoaiByAJuZQlMYElZRAbylqg9RBWDsqeefIwUgBfAbE4OiBUiIQBtNPBQK4+b+SkPPoOwRpL1YwxFwGQ8dicQ23PO/OHCAfhCtRdG6NBGJNPt8q8T8gDqKCsB59w1clmpgdvbzivrVp59++tBzzz9HLOIWb3zXJ2b+0Cgtv3bw4JOY8kOp57F/63s2I0Uwm4jYD9BbUWRVsBaggQM7tuuz/eTymbsPa2vZ3GJIH7CxzlfzgKUZkFBNIQAKsK0GZigEVM6TZedvPlgb+COi+iAJAJ7+CdXfQ+SBUtbAQTyJ1MQQ2FeUxj7iX1BuB3oBDyEPXC26d8fWTVtNknOJlita6vv1Ajt/axoQQUfQxyzNgIRqSgJFDmA7IKSiDmDu+36l5WvE1yGeC1RLdBjzvZrAWJBEH/PfEt6coE3T/vFqHuT7eUXuYHQTX+yZQzpBFGi5oGAl3kwB6pSaVb+de3PlRQTwtsNqAXbzA8hagDyk/Mhm/0pR/4CYwnSgPOqrFbd5ZuaMGiBB0+Kdwv63kf3rDJuvH9TL5i6CEAAWFA3gBiTBOtf6JiDKco/1BQFcFey7/3COA1g0Caxk8lR2wAPY5AC4MqiSDmD+YUX9Iwjg+ef/AdY6ElDXM8U6uHWYhNEXrFWU5o3bE4kFJo8DdNppjU0rhFwoGBzYu4N4NahFgTfMhVxKo8dKPLGMNNVhhtjc81NNIQBk2PUGiiRQHlJ2ZOff9asPfV0IgCsBu/3+jgQlgQgK4FOQrWl70PzfOEj8cwJgYdxgnffhePGiIRMq0IMkMHZAegFBNGCwbxQEDM+vo131+Xx/dkcCcFY1kHMAmxAghoVXTgF/QxHgEPH/3PPP/zGRlOj1811/AMHjk+ggTgwFSQBro7gu1CCWjtDNXRxqjRkS5g76TJLODmsUEDCpxyKPeYn2OsV3/wu5EaDaPIB9X8B0JQeEzM1/QVGfJNuEAJ4iiigHDAyZST469zH+Z/d6RVVCPTswGkjavzlc2AIZDhaGAR30j8TtQCXfIi/kDbkkUEF6f/EAIuEQOYBfWnjhVDEBTDswBzhToCWwgvz/9GGlhaI6BPAcGNrX4l+PGSJNIH7HH1KU2lAUU8da7F+AyOYOAzZ/FoV0BAvcgwA5k0LTPxEKmT/GAtX4PqBPDWSgmACq5MqgZDp9LVsxBWTnv7da7YRZkwCe4Z6g9WrrfrBssCZ2qkqgb7s5F7h4nZyAkf3rkJvCFdh4Am3UmP4DS3rKlQRKQge8FMVIJKj4Vn06txmQUEwAzrsuAC2B+RNFiiuD5EHlBlUC/WofQj4J4BDVAhN7GtQO3OKJIAyZ+I/31iu1/p4d3OIrnIOdj6ejpdGjxAVayYJY4+3aPsm3ubCwXgDt5AB8n8gzj0WTwEo2oZQdVAso2A5QsZ/xuBoaJmLHDj3D88FjBpiBA5YIQAnAKKb9DIR3IP+XMLkmgFqdZikNsanvtOaGlEMeEKRL7vWVAKlACsFi/+QBGhWf70PmFUE6inqAjOPmB7BtCazkdQFzmBNgPaZ4ldASnSQAbtCX/JEAdoP/PuPenyYkrUQ5WKcndphcC+Al2se6YGj7iVHJumH1oqBv0jr3FcoAFN8v5lnH4jlABRvRKwDbASEkgIrVArLZmw+rnAMKUI7XoQa3WXJAcvq7A1QB6N6OG0cyOPvXaZYb1l3SN+iVBGM3lygCjPIUcIbdG2RLyg3mCbIcwU1iah7Q54azYPEcwDkugNsB0pNL2hCUnX93jUgBBChFXxMM7DW6gqCIYaoA+ju24a7hvOsQVwOYY07+rTDNXMZ+oQJzN0HbK9m3Mm0L84BIHaUAH893AIsKwFlDwng8QJ4HSFfwyqC5+e8pquU+TyQAVe3EncGZOIrXWvxRpV5pEhMD6lVAvKg/aQF+uYiZhOR+cx9B7mNou6wxX+eY17QQ20ZBB/oB5Z0Cc7FIDuC48QAFhoRVMAT8P2pgRHh8MMQC6DZ7AjQt3levqs24F5S+U2fSMGsuWAg3XqCSSb3cq+EqYBkBJMk63Trn+prBGxFkAOa0IBYsHgLkL3UCKAbYeQBRC5DHlBfkWT6vrEcdQIc2oPrDukNArQ9XgKzfLNv/CCa7JphhWlhEYBaw04wUWmKr0Sm8GIzRAMgAfKuslwMYKJoEOnBEUOFaQEV+yFx29vcVyw3A0OevBvqNHZgCTFHXxzBdoMX7I7IjE7A0/ukEA2b9EJAHCGjaVtkVIJbEcI7dY2EUDEQaKQP4L+wcQFEBiHYAqgfQuSMPqp/BFSsJ+orZgsPCK/Wtb65RMM0/7BQ0aVqv2iDqe4AW71SVwADZP/boPEpK83yBtPODT1ICKF/U3yIwqiUwDYBJvo4cuo0tfc0O4P5HFnYDMIoJAH0BcwRoAM4OOkBEWLFRoUAOIHoD5THlRXb+ptowDHqFfRNDvSru/ALiaHe8V1Ea+g4Yr5uE8vzh4Npo7ZXxHkoSOsCOHJFo2gj3A7EAhAgYOYQbWjAKsTBXAXKHgulYLAe4JRSQzc7S2WUVVMiZlgXFcoAKfeu/RzMQHLygKpFoVTfwgF9UACgB4JSQ7Z9hBnPgIEh+kn2BdXcu9OYAwoFNGAtgUk8cmzQDNuxjLDAcwIu2/BcPAZnxdPLo2Zn33rtxY5Z0MM9S4DWd6oo51buHSALt2wHkIeUFnYf/lwWggzxAyL9hP+3AQxteX6+2iAqgBYJRnVZy91Q0SEaBVGFavv4KugCMScBYBCbJXMqVAiD3tNfV1Pg+lbQLAIsIgFzAxPj4+ER68pXLV65cuToDGUACelhAekABYYVIgb5LIQ9QoVogfeqX1ZY41wKZKKoFrm/oFDuo3EIJ4B7akApgWg2qqYRt3ncQ48Yl6/oB7FPMo7XEDjZ+3f5z+c7f0vdEwiHFV3N/Mq8XQKCoAJLJVCqdTmfSaeggPXXq5MnjZ9+4RTKACOANSAd0bqUGll0H9H3Opm3GA6A3sDKJCy4KM+eCIrYS8fX+jTr/vZQAbkYzsXydIAllJ3AICQBBLMRMMF+TB4gVS4JSQph/wjR/MwgQy+IhkbMhQQ5A8b1gWwUgFBUAg0QAZNITkMEE/tIvnrn6/q3bt9khyLgAX0CF5XQI+Aa2YwL5yqDKfKvZL6p9ohkIQNrHAmAF7A75AwMaNwCDTxH+TbPGTCB6WQCtv7B72mcoQR6g7dXN3yA/D5J6KQJdCLg7gHVeuAVYXAACSXiDVIb+SAikg4mJVOrouTffvH71ndvsEGRMwJnGuggqpw/6GnYhoHK1gOzc7BeCVMnjhF4QNRwK9EMRWmKkRVU7KQHMzf91XgXY6VtdPdYcDHiiGBg/oMW3g3/mHgtbEeSZPu+JNNfU1az6hPWK8ByUKgAGVJBMTcIdcGQgX5CePnXy0qWzb4jqwtwcOQXIgKsLfM7NReVB/7JAbyAcVEVw88EGMembgKYNBXA3CDQBdqq4P6gRHwhMN1FLeb+e5QmW5YYAmIcK9AqDNpbYIS8RNIm3SkCavChJ6KVIWx1VAT5l0w0ocUcCkDhMQoAS0pQgkAqmyB0gVUy+euE2EQ8ZIBpQvREhgWTATmEpAA+QtpklrILtADcfDOyxtARTxc8f2oJqnzakKI27KQCwAxBUSnuGeevxnyBMnekmIbAWeHGQ38nRn+gG4/rTiqZ2WdDBcjCUwL2Avn9SKAO4OwGY4LiAsEBxIU06oPrCkaNvXr/+zgzFBQQGsUBmwD4BWpCnriIoMCqYBVCZfwwBwOPLyjoEsGELGv4oAAQGErIJ0AIcR4ybST/eCg0g6sM56LpgkPXvI++fRzsj0t7W1K5PB2tQLgpyk5sAVv1CwQzgXgUgIPIDqjBwZIAOJo+du3T5/IULMkuEQ+AMAX8sA3n6ygt4n0JDwioSheiX3HyQLwLSAz2afrpIAInRTr+/dx+7AvIP4g98moAHMDTAS9YGC0GA3sPB3w6Rje3Na4n+CAtAZ99QgQ7RBJB7PXAuyiEAhogLkMFUOpPhaiMp4cSJl18XrQeIB3AHVFeXzkCexTKCFGBbC6iYB8jO/8eHWy1GPpoYG/CTABLacFBtjA5hPjDaCSbtRGDVgwCigyjRa9ooWv6tAhDmHom1N9XV1bXpxi8B9ulp9f+4FMT3gWTBDJBQNgGYkELIkD+ACkgK44fPnJ95b2bmfUgBMhAugUrl5AUfVqgWUBn+6V/+hzW4DziTxlE8MdAAAQwH1NDw9r6upr6+gaEn9sShBA3xAE8Gy0EbfRKuA3NCSgiJIImk1H/HZn0OoCimholGIhs3drc11anBYF7oz4XQQKSppqZm1a/k307ZggoIQELGBbQkUYKAGsOR45cvX75wdYYdglACS0BAntN7AeUahfsC5DFlxo9IAMQYxXHiEJwONIS3oA8QCUB859ZY17oNgUBT16MkhIHhBOmAHIKUAcqJ0cSTCZKB3MfU40EaIucfHcQ8UGA/2tPe1tXUHAwGVXXtuvaNPCugDrZ73fQF90CkSSUH8NGcOaHyUDkBAIeTh0kG9MhQWMjAG6QzUydOnnrltYuzoF+kBxYd3FtgoI+ymyOIrw6ukAf4wZrmnJq+NhCIbUnsDvlFC0Aivm1Tf3hjy9qAGmwIhh5a3/jowMAfDA3HiWGQTyvKF6ALWpEAqIhXtJHNm9n0wX57V3tbIADmFdxRet3GiM0MQTqsGuAE4IFvFuW/wgKwQMaFKfgDrjWmUy+//s77779/G1KAGJDDSRXcJVsiB8gXQMWqgdn5H6wx5oQmUGHAH9sRb1VD6CJEckDMbsNMP/3dzc0NgQZVxaRv9Q2BQKC376tDhN179owAw/yHwr7dA93t7e2d7e2hYLDej6khMT1gMBhq3hiO8ZygeRIw7V6HSABWFegENLBkApBgHUwiP6C4QDrIJE9fuvKm6GeCDkgEqDFCCXfedkBvtg0BFWsKJgE0DDHPEpo25I9tGfAHnoAjxw7IQIvv37Fl2+atg9HudeuaQ6GA6lfrFcwACZsONoQIgdBDAV6vCYXq6+tq62tVvok8oAYCa5vWdTP7NrcBkeTTih9yM9JICUCxJiCBpRYAgAoD3AHliag4jk9MZdDPdO7sBe515sDAWsCKKo4lg1gu1A5QmRwAHmCI6RftAOTFn2gdHAhw/wDvZxGwCigliI/sHd47OBgLd3d3EdXCqZNtEzABrEKskyRqsQfc0yoQCHW0d3Vv3Bjuj0izzzV+k3y9KBCJBOAAPvpN22FAFiyHAKyACjhP5PoCPQ6/duHWrVn0OBKkT4BbIDksxiEcR6Gm4Mo4AHiA3XoKwEmAtmdDrBUXh5pxAVk+bcBRQAbQQhwTfcTCPYS2ACUH9GygKI8ZYmklSl093T09nP+LeaDz3X4+TA1EmkQLQIFOYBPLLQCGpcKAhqTxTOqVs29ev36V2xORJkolcHzAiRfnPw+oBdh5AL5hhDymrIAH2A1m2f7Z4Y90djcEMEWUIQCzgBLqd0B8H2b8YVr74dbh2SnroxXqe7H+aLQ/GgvTJgd8O/JJQ4JwWhrMy0JkXQ3Zf+0n0/IcFMaKEICAkMFkegpNimhBmDx17tKlc29cZWfA3HOSiBQB3l6SYIL2284PIJLAiiiAQ4Ax4I+gJXpDDegDlpDK0CFaBckjoDYY37uNKMdNHugvSl5brIh+2qEbfYE5YS3NQzr5uS1AlADU/pd5xpCPFSQABuUHpAJ6ykQRPU0npqZefgPOQMiAcwOuPgpIKgAeD5DvAaYwP4A8pIyAM/rbNbth4nqHHpn2Bp4twDD7BWCpsHuAJ0gYlMH69aUoEvF2dg+AfX6n+XZRktuRthqlFjMCLpYAEFaaACyQDiFNNUfuYMi8cOby9ZnrM2IcCgICCwFugZjgZ4FBoRW8c+iPEAKYWs4AxhIjofVUA+Adul8Q1wKaXsKEJm71WBr40NymYcAQgVEg+5ddAIvzv5IFIKAHBlJCZnxiYir1ysnLl89fuKh7BDNBIIrRHWyfA1SqJfA/PGQdDkBG3afiKgBmG+5f1A4WBgK5puONCZ+Kgg7CcVICBtfGyuAeiKwL1viKjgGwYsULAOB6I4SQIRkQxsklnDh14uhr78hqI0cEht14gApeFzB/80FLLYCIHw5t4PFAcs8C5AoBx1moM+i1QI4Dk3ux0g/I4TwHiP+K7+eTeSfCFo4QgAXsDzKTouOZUsXpw0dfx7h1xAVooHA7QGUUcPPBIQvbmta7fgsteYOMX/b26r2+DBKBRQdb4ALEQ3Kbsy12McyiLEEC9LSsgEh7jUIVgJ//VgnxH3CaAAQ4LmTEyDQ0IUwdOXeex63fss0BKnjPICkAndI9gT5jdhg4BswUjn5CKosRXlYtYL5gPQSYK/GQG+bKXHJJvpaHSFtdjVJT8/FvlRL/AWcKQEIfgZDKZDD+YHrq1MmpIr2BlRABQoDOOIYBtcR1ByBAfAtxWKxeFwO9A5P9SC5zKDU3uGRziG7xhgtghJtQ/8eM4CUlAARHC8AAZAAloIMhT/lSAJwsZktpUbwT3PzCHksOsHvtbq7iwboXuH0G9rEf4C2Syl7Bm0Gwhe4FRXoae8RewJQBAyMAKf//9AuLNwDpqA4BSEAE+Z6PBHBBZIhIErjWqNcdy4AvoCFIQtvQayQEpACdaikFKjLxhjJGx/QZHwlired7+Ut9JdZMvLmQaF9L8b/m/l+gjFn+9sVRVQKwRzKVPnXp3NmLN3B9K1SAKgNVGunJ7cr3poTPY1ZY9gGatqdlxJIRAsy/8BA672JeAEbe1R7WlfECtniPsVpg9zrCdTwE+FfICjwBWIFkcQKXNB1+8bWr8voFgCQgFuQR7loFj+EWscQlni0DtGIFSGs3w8BBkf5J5mH9dKSY7UvCLOVwTpBbWBH1cr8QgSmFCK4AQPv/Py45/DPcIACuO2YyaFKkHGHq8NHLV69ff0d2Pc/Pwhegc8G2f2FRfKVJDwHa7hZcJyy3AEm3wTqBVCA3tbGEwb+kWCzlPoncrcIIN5H5qzUP/tfFR4DlwRUCAERbEl/pmpmYmJqcPnnp0vnXjQZFPUGAR4AWJL2L4/9v1QUQ79CvEzeNXzYFGOmA/hKEgnZgS9pnMA2rFjuwlDZORXkA7RAP/SUAvT+Kqvge/O6RYkOAbeAaAUjoY1FICBnuaJqYOnpaDEcSsYDSAiQJ7A9K8Qg3pQC0saEBq/Ublo61XpSqEG+IGwQa3BuFXOi7LYwvAJm/qqo1X7o598qdOQDXCcCAaFJMZzJT6GOYOnz6wvWZmZkbpitgPbAIisrgZktCuoDeEV4dOiT8vCDbQG4KQPwniFcwK9iV3G6ybJovWpRhasAskfmr5P3V1f8XCflYiS2AOlwrAIbsYqDkgBsVp4/xwPV33if6TZcgdEAysB2cNvvfyyRwuA+8PvXM8889I3kmEaBkaRIWKzp6VNuLC/4IvBRk6pSa1DIGxQ4scgsSuEqE6Fd+7wf4zp4HuGNQVCAhZNCgiCQxkzlx6tQrp9/QL1/QlYCgwK2JC3TwRY782thGcgCjzzwPCL5zXYDF+AHzcm87EL86zVaqbcHmryjKl39KX9ATwL1ApgdwCGJg2gunr828//4NOVEWQQxAyNXA/7iDI8DIHlo89RwLgC/v4ktFJO857Gu45keyxxpgjqlA64KSyBGDKYoImz/h4f97lr2VJ4B7hwgL6dQUPMJEOvnKOXPcutQAUgM9M/i7PRjbM7YXA8OeYv6fMW2fSoJ8Y9eoNhbfx5N9mmTnlHJYlhtYWYoG2ptR9VNqVj/2rshUKAfwBFAWcFhAjyN3OU6ljh3DuPXX9XHrhj+Yn393AEYtKgAsgGfE3C+AQb7hAmD+mw3yaSVLObwaW7y2vmQts/WT+deoX/jeTfoiCFBzWc8DlB2ICnwBAw9Mm3rh9Yu3bvGwdXYI8zf/N70hANd2g38iHNkfJv62XO7PB2lanKf6JOSuGKBXUkwrg2wr6wYiEU79qPa/+juzeoM2JaqeB6gQSAXkEniA4vhE6sjRK29ev3r1xm3KDf8/HgEmRHDoqadIBQbpFtN/8uAosT+yjSd6FKxjyaUFl3XmEG7LPll/O6yfBLD68Z8w9RCAlwRWGKK+AHC9MTV98uSlc+f/jWwIIK5BPlOOMtYS2iiu+Y1vI+dvIV8W7VBUA5Fw+1q4fkVVVz/+vVlrU0XWE0DFYaogk4ZHmPrneksQcFD2/VmAVzUtsWMzES4FYIqAnoJfWqJgIVvu0aGX0etTV1cD81e/8GNJPLw/FuQBvIagpQPrYOovRsxbBi0EhofgKqDtmwzyAUsRsPJMWLBpBRl/E1OvUOx/7Psm9QIUAzwPsMRIppP/CteBmE6AwDYP7hNaYngHbvZrUq5nAGJHCdyb+0TeTzU/ksCDj1PNH5QL6gU8D7AMSL/0r/bjkk+deOOhjQ7voKgP6k3SdVi2BcE6zbRGUaz0nYRIZOM6zvsUOICH/x1X/HLpx7bnAZYcmfE/HIljvg8SAT1wAXDiQHzHDlAviZdsQwpyQ+wx+ZUlC+FWRNjzc+CnxE998PPfBf35fROUDM694nUHLzEmp35nZM/2/Xt3bNm7c8uWbVu2bB0EJHc6rNs5rxXg3ATV+JqaebAHsV+jrvn8X1PmJzom8uBVA5cBqfT0//5vf+2f/UG/AVzWWeC6Tp17Wi+UiB3I8lHfZ9uHAPy/9+132fitmZ8JbgfwPMBSA60C4/T3y//dZ/t6+8PhcH84EuGZvTC1G3iUl/veCSIRWD6Tj74eYt+/+te/Q+Sz7dvSD3g5wDJANArw7BbJl/757/zqb/a2NHV1t3f3EIlRVgJWLIMozwNRHJF2Mvs21PUB1PjUGv+Dv/7Y37yrk1yYfq8vYNmQTCblLOqTk9/681/+px/7SKAu0BgKNba3d7dDCiYwHYSuA97gHeTtifjmRmH1NXpDPy0f/sJ3vk+OH6aPAYtwAoXg1QKWG+QJJtPpVHp8/IVU5rc++nP3r/Kt8vnqAnUN+GvsxqxAG7s39mzcuLGHCA+HN+qmzqTX1NXQA1f31Cg1iqL4V3/mb358k9J9Zr8I8xKeB1gJ4JCQEfhmMvV//NqnPv2hD37wgQ/V+3zMLZPMPIuVZB+sC/jqa//Rf/aZ/+rL3/neT7jPkf/g+RcTACZI8HoDVwS4uwCDCaCE9PS3XkgmX/ok4Xd/44EHHvjAB+rrSQ2kBx/zjWdtbX39/Q984IGf/00c9smX/u3/ee6Na7fkVSw8Ig1LGf4LC8HzACsIoteIhJAkEbBLSGemp+Ecko/82TRePEJ/k/L5wiOPvJCZzmSm0zz5AYYjpU9MTb58EQOVhQqokifcAQYo5jcDCQ/gCWAlIiUCA3sF+AUSBC2mhC5Sacx0kEkjcgAQDaSDQ/B6+vCRs+ffm5nhSfOkAJAWsEfIiQuIE15fwIoG7J7JlQULaB8fwccxqAgZUF4JqUy/cg6TI80YFzeSuQtngByRdcANQZ4HqDIYd+Kg8EAh5MSp46+8iivaiGzQT+xT3ZCKVOKmYM8DVC2kEhAV0unk0aPvYG4kdggYniok4XmAaodQgUgkMqkXjp+/cuUa34OD6fcE4BJwXBC3cMykktPHT548/tpVThK9dgCXgSua5BA4Mrzw4utHPAG4EUlZX0BlUu4qEZ4AqgdJzLR9Z/bvCcD18ATgcngCcDk8AbgcngBcDk8ALocnAJfDE4DL4QnA5fAE4HJ4AnA5PAG4HJ4AXA5PAC6HJwCXwxOAy+EJwOXwBOByeAJwOTwBuByeAFwOTwAuhycAl8MTgMvhCcDl8ATgcngCcDk8AbgcngBcDk8ALocnAJfDE4DL4QnA5fAE4HJ4AnA5PAG4HJ4AXA5PAC6HJwCXwxOAy+EJwOXwBOByeAJwNX72s/8ElxpTDPOvHI8AAAAASUVORK5CYII='
$IconBytes                       = [Convert]::FromBase64String($IconBase64)
$Stream                          = New-Object IO.MemoryStream($IconBytes, 0, $IconBytes.Length)
$Stream.Write($IconBytes, 0, $IconBytes.Length)
$Form.Icon                       = [System.Drawing.Icon]::FromHandle((New-Object System.Drawing.Bitmap -Argument $Stream).GetHIcon())

$Label1                          = New-Object system.Windows.Forms.Label
$Label1.text                     = "MAIN TWEAKS"
$Label1.AutoSize                 = $True
$Label1.width                    = 230
$Label1.height                   = 25
$Label1.location                 = New-Object System.Drawing.Point(125,12)
$Label1.Font                     = New-Object System.Drawing.Font('Microsoft Sans Serif',24,[System.Drawing.FontStyle]([System.Drawing.FontStyle]::Bold))
$Label1.ForeColor                = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$Label2                          = New-Object system.Windows.Forms.Label
$Label2.text                     = "EXTRA"
$Label2.AutoSize                 = $True
$Label2.width                    = 457
$Label2.height                   = 142
$Label2.location                 = New-Object System.Drawing.Point(190,300)
$Label2.Font                     = New-Object System.Drawing.Font('Microsoft Sans Serif',24,[System.Drawing.FontStyle]([System.Drawing.FontStyle]::Bold))
$Label2.ForeColor                = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$Label3                          = New-Object system.Windows.Forms.Label
$Label3.text                     = "Made by Xercaii  *  @Xercaii On YouTube"
$Label3.AutoSize                 = $True
$Label3.width                    = 204
$Label3.height                   = 30
$Label3.location                 = New-Object System.Drawing.Point(115,540)
$Label3.Font                     = New-Object System.Drawing.Font('Consolas',9)
$Label3.ForeColor                = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$cleartempfiles                  = New-Object system.Windows.Forms.Button
$cleartempfiles.text             = "CLEAR TEMPORARY FILES"
$cleartempfiles.width            = 204
$cleartempfiles.height           = 30
$cleartempfiles.location         = New-Object System.Drawing.Point(40,56)
$cleartempfiles.Font             = New-Object System.Drawing.Font('Consolas',9)
$cleartempfiles.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$disablestartupprograms          = New-Object system.Windows.Forms.Button
$disablestartupprograms.text     = "DISABLE STARTUP PROGRAMS"
$disablestartupprograms.width    = 204
$disablestartupprograms.height   = 30
$disablestartupprograms.location = New-Object System.Drawing.Point(40,86)
$disablestartupprograms.Font     = New-Object System.Drawing.Font('Consolas',9)
$disablestartupprograms.ForeColor = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$xercaiipowerplan                = New-Object system.Windows.Forms.Button
$xercaiipowerplan.text           = "XERCAII POWER PLAN"
$xercaiipowerplan.width          = 203
$xercaiipowerplan.height         = 30
$xercaiipowerplan.location       = New-Object System.Drawing.Point(40,136)
$xercaiipowerplan.Font           = New-Object System.Drawing.Font('Consolas',9)
$xercaiipowerplan.ForeColor      = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$powertweaks                     = New-Object system.Windows.Forms.Button
$powertweaks.text                = "POWER TWEAKS"
$powertweaks.width               = 203
$powertweaks.height              = 30
$powertweaks.location            = New-Object System.Drawing.Point(40,166)
$powertweaks.Font                = New-Object System.Drawing.Font('Consolas',9)
$powertweaks.ForeColor           = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$networktweaks                   = New-Object system.Windows.Forms.Button
$networktweaks.text              = "NETWORK TWEAKS"
$networktweaks.width             = 205
$networktweaks.height            = 30
$networktweaks.location          = New-Object System.Drawing.Point(40,216)
$networktweaks.Font              = New-Object System.Drawing.Font('Consolas',9)
$networktweaks.ForeColor         = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$usbtweaks                       = New-Object system.Windows.Forms.Button
$usbtweaks.text                  = "USB TWEAKS"
$usbtweaks.width                 = 205
$usbtweaks.height                = 30
$usbtweaks.location              = New-Object System.Drawing.Point(40,246)
$usbtweaks.Font                  = New-Object System.Drawing.Font('Consolas',9)
$usbtweaks.ForeColor             = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$ramtweaks                       = New-Object system.Windows.Forms.Button
$ramtweaks.text                  = "RAM TWEAKS"
$ramtweaks.width                 = 205
$ramtweaks.height                = 30
$ramtweaks.location              = New-Object System.Drawing.Point(255,56)
$ramtweaks.Font                  = New-Object System.Drawing.Font('Consolas',9)
$ramtweaks.ForeColor             = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$disablenotifications            = New-Object system.Windows.Forms.Button
$disablenotifications.text       = "DISABLE NOTIFICATIONS"
$disablenotifications.width      = 205
$disablenotifications.height     = 30
$disablenotifications.location   = New-Object System.Drawing.Point(255,86)
$disablenotifications.Font       = New-Object System.Drawing.Font('Consolas',9)
$disablenotifications.ForeColor  = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$disablecortana                  = New-Object system.Windows.Forms.Button
$disablecortana.text             = "DISABLE CORTANA"
$disablecortana.width            = 205
$disablecortana.height           = 30
$disablecortana.location         = New-Object System.Drawing.Point(255,136)
$disablecortana.Font             = New-Object System.Drawing.Font('Consolas',9)
$disablecortana.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$uninstalluselessapps            = New-Object system.Windows.Forms.Button
$uninstalluselessapps.text       = "UNINSTALL USELESS APPS"
$uninstalluselessapps.width      = 205
$uninstalluselessapps.height     = 30
$uninstalluselessapps.location   = New-Object System.Drawing.Point(255,166)
$uninstalluselessapps.Font       = New-Object System.Drawing.Font('Consolas',9)
$uninstalluselessapps.ForeColor  = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$ctt                             = New-Object system.Windows.Forms.Button
$ctt.text                        = "CTT"
$ctt.width                       = 205
$ctt.height                      = 30
$ctt.location                    = New-Object System.Drawing.Point(255,216)
$ctt.Font                        = New-Object System.Drawing.Font('Consolas',9)
$ctt.ForeColor                   = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$windowsdebloat                  = New-Object system.Windows.Forms.Button
$windowsdebloat.text             = "WINDOWS 10/11 DEBLOAT"
$windowsdebloat.width            = 205
$windowsdebloat.height           = 30
$windowsdebloat.location         = New-Object System.Drawing.Point(255,246)
$windowsdebloat.Font             = New-Object System.Drawing.Font('Consolas',9)
$windowsdebloat.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$xercaiiyoutube                  = New-Object system.Windows.Forms.Button
$xercaiiyoutube.text             = "XERCAII YOUTUBE"
$xercaiiyoutube.width            = 205
$xercaiiyoutube.height           = 30
$xercaiiyoutube.location         = New-Object System.Drawing.Point(147.5,344)
$xercaiiyoutube.Font             = New-Object System.Drawing.Font('Consolas',9)
$xercaiiyoutube.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$xercaiidiscord                  = New-Object system.Windows.Forms.Button
$xercaiidiscord.text             = "XERCAII DISCORD"
$xercaiidiscord.width            = 205
$xercaiidiscord.height           = 30
$xercaiidiscord.location         = New-Object System.Drawing.Point(147.5,374)
$xercaiidiscord.Font             = New-Object System.Drawing.Font('Consolas',9)
$xercaiidiscord.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$xercaiipremium                  = New-Object system.Windows.Forms.Button
$xercaiipremium.text             = "XERCAII PREMIUM TWEAKS"
$xercaiipremium.width            = 205
$xercaiipremium.height           = 30
$xercaiipremium.location         = New-Object System.Drawing.Point(147.5,404)
$xercaiipremium.Font             = New-Object System.Drawing.Font('Consolas',9)
$xercaiipremium.ForeColor        = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")

$userestorepoint                 = New-Object system.Windows.Forms.Button
$userestorepoint.text            = "USE RESTORE POINT"
$userestorepoint.width           = 205
$userestorepoint.height          = 30
$userestorepoint.location        = New-Object System.Drawing.Point(147.5,434)
$userestorepoint.Font            = New-Object System.Drawing.Font('Consolas',9)
$userestorepoint.ForeColor       = [System.Drawing.ColorTranslator]::FromHtml("#eeeeee")



$Form.controls.AddRange(@($cleartempfiles, $disablestartupprograms, $xercaiipowerplan, $powertweaks, $networktweaks, $usbtweaks, $ramtweaks, $disablenotifications, $disablecortana, $uninstalluselessapps, $ctt, $windowsdebloat, $label1, $label2, $label3, $xercaiiyoutube, $xercaiidiscord, $userestorepoint,$xercaiipremium))

#Main Tweaks
$cleartempfiles.Add_Click({
    Log("Clearing Temporary Files....")
    Start-Sleep -Seconds (5)
    taskkill /F /IM explorer.exe
    Remove-Item -Path $env:TEMP\* -Force -Recurse
    Remove-Item -Path C:\Temp -Recurse
    Remove-Item -Path %temp% -Recurse
    Remove-Item -Path C:\Users\Isaia\AppData\Local\FortniteGame\Saved\Config\CrashReportClient\CrashReportClient.ini -Recurse
    ipconfig /flushdns
    Remove-Item -Path *.log /a /s /q /f -Force -Recurse
    Remove-Item -Path /f "%temp%" /r /d y -Force -Recurse
    Remove-Item -Path C:\windows\temp. -Recurse
    Remove-Item -Path C:\WINDOWS\Prefetch -Recurse
    Remove-Item -Path %systemdrive%\*.tmp -Recurse
    Remove-Item -Path %systemdrive%\*._mp -Recurse
    Remove-Item -Path %systemdrive%\*.log -Recurse
    Remove-Item -Path %systemdrive%\*.gid -Recurse
    Remove-Item -Path %systemdrive%\*.chk -Recurse
    Remove-Item -Path %systemdrive%\*.old -Recurse
    Remove-Item -Path %systemdrive%\recycled\*.* -Recurse
    Remove-Item -Path %systemdrive%\$Recycle.Bin\*.* -Recurse
    Remove-Item -Path %windir%\*.bak -Recurse
    Remove-Item -Path %windir%\prefetch\*.* -Recurse
    Remove-Item -Path %LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db -Recurse
    Remove-Item -Path %LocalAppData%\Microsoft\Windows\Explorer\*.db -Recurse
    Remove-Item -Path %SystemRoot%\Logs\CBS\CBS.log -Recurse
    Remove-Item -Path %SystemRoot%\Logs\DISM\DISM.log -Recurse
    Remove-Item -Path C:\Windows\Temp -Recurse
    Remove-Item -Path c:\windows\tempor~1 -Recurse
    Remove-Item -Path c:\windows\temp -Recurse
    Remove-Item -Path c:\windows\tmp -Recurse
    Remove-Item -Path c:\windows\ff*.tmp -Recurse
    Remove-Item -Path c:\windows\history -Recurse
    Remove-Item -Path c:\windows\cookies -Recurse
    Remove-Item -Path c:\windows\recent -Recurse
    Remove-Item -Path c:\windows\spool\printers -Recurse
    $Devices = Get-PnpDevice | ? Status -eq Unknown;foreach ($Device in $Devices) { &\"pnputil\" /remove-device $Device.InstanceId }
    Clear-RecycleBin -Force
    start explorer.exe
    Log("Successfully Cleared Temp Files!")
})

$disablestartupprograms.Add_Click({
    Log("Disabling Startup Programs...")
    Start-Sleep -Seconds (5)
    Disable-ScheduledTask -TaskName "Microsoft\Windows\Setup\gwx\refreshgwxconfig"
   Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Startup Programs!")
})

$xercaiipowerplan.Add_Click({
    Log("Enabling Xercaii Tweaks Power Plan (FULLY OPTIMIZED)...")
    Start-Sleep -Seconds (5)
    powercfg -duplicatescheme fa2c13f4-ada1-4ef2-b4a0-0143d733bb2a
    Log("The Operation Completed Successfully.")
    Log("Successfully Enabled Xercaii Tweaks Power Plan")
})

$powertweaks.Add_Click({
    Log("Applying Power Tweaks....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\GpuEnergyDrv" -Name "Start" -Type DWord -Value 4
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\GpuEnergyDr" -Name "Start" -Type DWord -Value 4
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy" -Name "DisableTaggedEnergyLogging" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy" -Name "TelemetryMaxApplication" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\kernel" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Executive" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power\ModernSleep" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power" -Name "CoalescingTimerInterval" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power" -Name "PlatformAoAcOverride" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power" -Name "EnergyEstimationEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power" -Name "EventProcessorEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power" -Name "CsEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling" -Name "PowerThrottlingOff" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Applied Power Tweaks!")
})

$networktweaks.Add_Click({
    Log("Applying Network Tweaks....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "SystemResponsiveness" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "NetworkThrottlingIndex" -Type DWord -Value 4294967295
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "IRPStackSize" -Type DWord -Value 32
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "DefaultTTL" -Type DWord -Value 70
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "TCP1323Opts" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "MaxFreeTcbs" -Type DWord -Value 65536
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "MaxUserPort" -Type DWord -Value 65534
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters" -Name "GlobalMaxTcpWindowSize" -Type DWord -Value 65535
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{c36af243-1958-4434-ae35-94c10b4feb40}" -Name "MTU" -Type DWord -Value 1500
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{6c590aec-4a52-43c4-8617-9ee7e4b08441}" -Name "MTU" -Type DWord -Value 1500
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\{02bf9c57-82bf-452b-bdf3-a2f5fcd13144}" -Name "MTU" -Type DWord -Value 1500
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters" -Name "SizeReqBuf" -Type DWord -Value 17424
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces" -Name "DisableTaskOffload" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Applied Network Tweaks!")

})

$usbtweaks.Add_Click({
    Log("Disabling USB Power Savings....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "AllowIdleIrpInD3" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "D3ColdSupported" -Type DWord -Value 0
    Log("The Operation Completed Successfully.") 
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "DeviceSelectiveSuspended" -Type DWord -Value 0 
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "EnableSelectiveSuspend" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "EnhancedPowerManagementEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "SelectiveSuspendEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Enum\%%i\Device Parameters" -Name "SelectiveSuspendOn" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled USB Power Savings!")
    Start-Sleep -Seconds (2)
    Log("Applying USB Thread Priority")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\usbxhci\Parameters" -Name "ThreadPriority" -Type DWord -Value 31
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\USBHUB3\Parameters" -Name "ThreadPriority" -Type DWord -Value 31
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\nvlddmkm\Parameters" -Name "ThreadPriority" -Type DWord -Value 31
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\NDIS\Parameters" -Name "ThreadPriority" -Type DWord -Value 31
    Log("The Operation Completed Successfully.")
    Log("Successfully Applied USB Thread Priority!")
    Start-Sleep -Seconds (2)
    Log("Disabling USB Selective Suspend....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Services\USB" -Name "DisableSelectiveSuspend" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled USB Selective Suspend!")
    Start-Sleep -Seconds (2)
    Log("Enabling MSI Mode On USB....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\System\CurrentControlSet\Enum\%%i\Device Parameters\Interrupt Management\MessageSignaledInterruptProperties" -Name "MSISupported" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Enabled MSI Mode On USB!") 
    

})


$ramtweaks.Add_Click({
    Log("Disabling Paging Executive....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "DisablePagingExecutive" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" -Name "DpiMapIommuContiguous" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Paging Executive!")
    Start-Sleep -Seconds (2)
    Log("Disabling Prefetch And Superfetch....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters" -Name "EnablePrefetcher" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters" -Name "EnableSuperfetch" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Prefetch And Superfetch!")
    Start-Sleep -Seconds (2)
    Log("Disabling Memory Compression....")
    Start-Sleep -Seconds (5)
    PowerShell -Command "Disable-MMAgent -MemoryCompression" > nul 2>&1
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Memory Compression!")

})

$disablenotifications.Add_Click({
    Log("Disabling Notifications....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications" -Name "ToastEnabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" -Name "NOC_GLOBAL_SETTING_ALLOW_NOTIFICATION_SOUND" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings" -Name "NOC_GLOBAL_SETTING_ALLOW_CRITICAL_TOASTS_ABOVE_LOCK" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\QuietHours" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.AutoPlay" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.LowDisk" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.Print.Notification" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.SecurityAndMaintenance" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings\Windows.SystemToast.WiFiNetworkManager" -Name "Enabled" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer" -Name "DisableNotificationCenter" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Notifications!")


})

$disablecortana.Add_Click({
    Log("Disabling Cortana....")
    Start-Sleep -Seconds (5)
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "AllowCortana" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "AllowCloudSearch" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "AllowCortanaAboveLock" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "AllowSearchToUseLocation" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "ConnectedSearchUseWeb" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "ConnectedSearchUseWebOverMeteredConnections" -Type DWord -Value 0
    Log("The Operation Completed Successfully.")
    Set-ItemProperty -Path "HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search" -Name "DisableWebSearch" -Type DWord -Value 1
    Log("The Operation Completed Successfully.")
    Log("Successfully Disabled Cortana!")


})

$uninstalluselessapps.Add_Click({
    Log("Uninstalling Useless Apps....")
    taskkill /f /im explorer.exe
    Start-Sleep -Seconds (5)
    Get-AppxPackage *Microsoft.WindowsBackup* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.BingWeather* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.GetHelp* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.Getstarted* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.Messaging* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.Microsoft3DViewer* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.MicrosoftSolitaireCollection* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.MicrosoftStickyNotes* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.MixedReality.Portal* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.OneConnect* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.People* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.Print3D* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.SkypeApp* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.WindowsAlarms* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.WindowsCamera* | Remove-AppxPackage
    Get-AppxPackage *microsoft.windowscommunicationsapps* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.WindowsMaps* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.WindowsFeedbackHub* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.WindowsSoundRecorder* | Remove-AppxPackage
    Get-AppxPackage *Microsoft.YourPhone* | Remove-AppxPackage
    Get-AppxPackage -allusers *3DBuilder* | Remove-AppxPackage
    Get-AppxPackage -allusers *bing* | Remove-AppxPackage
    Get-AppxPackage -allusers *bingfinance* | Remove-AppxPackage
    Get-AppxPackage -allusers *bingsports* | Remove-AppxPackage
    Get-AppxPackage -allusers *BingWeather* | Remove-AppxPackage
    Get-AppxPackage -allusers *CommsPhone* | Remove-AppxPackage
    Get-AppxPackage -allusers *Drawboard PDF* | Remove-AppxPackage
    Get-AppxPackage -allusers *Facebook* | Remove-AppxPackage
    Get-AppxPackage -allusers *Getstarted* | Remove-AppxPackage
    Get-AppxPackage -allusers *Microsoft.Messaging* | Remove-AppxPackage
    Get-AppxPackage -allusers *MicrosoftOfficeHub* | Remove-AppxPackage
    Get-AppxPackage -allusers *Office.OneNote* | Remove-AppxPackage
    Get-AppxPackage -allusers *OneNote* | Remove-AppxPackage
    Get-AppxPackage -allusers *SkypeApp* | Remove-AppxPackage
    Get-AppxPackage -allusers *solit* | Remove-AppxPackage
    Get-AppxPackage -allusers *Sway* | Remove-AppxPackage
    Get-AppxPackage -allusers *Twitter* | Remove-AppxPackage
    Get-AppxPackage -allusers *WindowsAlarms* | Remove-AppxPackage
    Get-AppxPackage -allusers *WindowsPhone* | Remove-AppxPackage
    Get-AppxPackage -allusers *WindowsMaps* | Remove-AppxPackage
    Get-AppxPackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
    Get-AppxPackage -allusers *WindowsSoundRecorder* | Remove-AppxPackage 
    Get-AppxPackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
    Get-AppxPackage -allusers *zune* | Remove-AppxPackage
    start explorer.exe
    Log("Successfully Uninstalled Useless Apps!")
})

$ctt.Add_Click({
    Log("Opening CTT....")
    Start-Sleep -Seconds (5)
    Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/1133347325943758878/1210505212704464928/CTT.bat?ex=65eacdd4&is=65d858d4&hm=006d99b4aa601202888490cdca2745513c7b11b651c54c9d27fa0ee35fc266cc&" -OutFile "C:\XercaiiFreeTweaks\CTT\CTT.bat"
    Start-Sleep -Seconds (2)
    Invoke-Item "C:\XercaiiFreeTweaks\CTT\CTT.bat"
    Log("Successfully Opened CTT!")

})

$windowsdebloat.Add_Click({
    Log("Opening Windows 10/11 Debloat....")
    Start-Sleep -Seconds (5)
    Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/1133347325943758878/1211103530052755476/Launch.bat?ex=65ecfb0e&is=65da860e&hm=c04b0bc01ad1df5bc8f4e3595b311e37b8af51dbd0172074e215f70de4fec286&" -OutFile "C:\XercaiiFreeTweaks\Win11Debloat\Launch.bat"
    Invoke-WebRequest -Uri "https://cdn.discordapp.com/attachments/1133347325943758878/1211103612709900288/main.ps1?ex=65ecfb22&is=65da8622&hm=c89ab0e7be2345f342e4c22f6cb38a18bd441c8982f60f38f01a969b80500c38&" -OutFile "C:\XercaiiFreeTweaks\Win11Debloat\src\main.ps1"
    Start-Sleep -Seconds (2)
    Invoke-Item "C:\XercaiiFreeTweaks\Win11Debloat\Launch.bat"
    Log("Successfully Opened Windows 10/11 Debloat!")



})




#EXTRA
$xercaiiyoutube.Add_Click({
Start-Sleep -Seconds (1)
Start-Process "https://www.youtube.com/channel/UCHl2JkYEomnOn6sTAvXZ1lQ"

})

$xercaiidiscord.Add_Click({
Start-Sleep -Seconds (1)
Start-Process "https://discord.gg/6XpAu2RcsG"

})

$xercaiipremium.Add_Click({
Start-Sleep -Seconds (1)
Start-Process "https://discord.com/channels/1011097061883654255/shop"

})

$userestorepoint.Add_Click({
Start-Sleep -Seconds (1)
Start-Process rstrui.exe

})


[void]$Form.ShowDialog()
